### ISSUE TITLE
Python course resources

### ISSUE THREAD

**Issue by Rupam64** [appbrewery/100-days-of-python#14]
@angelabauer Mam, please revert and add all the course resource files back here(previously like web development Bootcamp) as it creates confusion and problems on udemy individually. If all the resources are stacked and kept in one place, then it's easy to access the files and understand the concepts in less time. I hope that you take the necessary actions from your side and keep on providing quality content for us. Thanking you.

**Comment by tamato27** [comment]
I Agree Please do 
Thx

**Comment by robo-monk** [comment]
**https://github.com/robo-monk/100-days-of-python** i've forked the latest commit with the links in the readme to keep it handy

**Comment by Rupam64** [comment]
@robo-monk thanks a lot for your wonderful effort. Have a nice day 😀

**Comment by mark8855** [comment]
@robo-monk thanks 

I agree with @Rupam64 

moving resources from GitHub broke my workflow for this course

I see some of us think the same

on the other side I found on Sunday that newest safari has a problem with opening course links on Udemy website (java enabled but crashing)
 ... and Udemy iPad app start crashing at all after last update ...

Anyway @angelabauer is the best, amazing teacher I know, so I took this little problem as a challenge :)

**Comment by yeskvr** [comment]
Can someone share the Python syntax cheatsheet and the coding notes page.
