### ISSUE TITLE
Cheat sheets and notes pages

### ISSUE THREAD

**Issue by dnyandaakarte** [appbrewery/100-days-of-python#19]
Could not find python cheat sheets and notes pages.
Please help me on this.

**Comment by shazzykazzy** [comment]
> Could not find python cheat sheets and notes pages.
> 
> Please help me on this.

Me too :(

**Comment by TheMuellenator** [comment]
They're found in the lesson resources as downloads (not on Github)
<img width="848" alt="image" src="https://user-images.githubusercontent.com/21653182/107628374-74f3f900-6c58-11eb-9bc1-465cb5b3a5e2.png">

**Comment by dnyandaakarte** [comment]
Thankyou

**Comment by Janhavi-Chandak** [comment]
please share cheat sheets
